Optionally download the latest codedx.war file
codedx/codedx-docker pull request #1
Opened 2018-12-14 04:40 UTC by stevesalas

When a specific version of codedx.war is not present in the codedx-docker/codedx-tomcat folder, this update to the Dockerfile will extract the codedx.war file from https://codedx.com/installers/codedx-latest.zip.

2018-12-14 16:11 UTC, iammobius1 requested changes
It may be best to split the `if test`, `wget`, `unzip`, and `rm` commands into separate docker `RUN` statements, for easier debugging via docker logs. For example, `wget` could fail due to a network error, but docker will report that the `RUN` step containing multiple operations failed, making it slightly more difficult to narrow down the culprit.

2018-12-14 17:24 UTC, stevesalas commented
Thanks for the feedback. Given the size of the codedx.war file, the single `RUN` statement avoids additional layers, one of which significantly increases the overall image size.

2018-12-14 18:09 UTC, iammobius1 approved these changes

2018-12-14 18:12 UTC, merged

2021-01-13 21:19 UTC, stevesalas commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/codedx/codedx-docker/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: